name: complexapps-2024
channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - annotated-types
  - fastcore
  - immutables
  - ipydatagrid
  - ipykernel
  - ipyvuetify
  - ipywidgets>8
  - markdown
  - matplotlib
  - jupyter
  - jupyterlab
  - notebook
  - nbdev
  - pandas
  - pip
  - pydantic
  - python=3.11
  - statsmodels
  - traittypes
  - voici
  - voila>=0.5.6
  - pip:
      - ipyautoui